mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  servlet:
    context-path: /jialong
  port: 80
spring:
  profiles:
    active: dev