mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml


server:
  servlet:
    context-path: /jialong
  port: 80
  tomcat:
    max-http-form-post-size: 2
  compression:
    enabled: true
    mime-types: application/json
spring:
  profiles:
    active: dev
logging:
  level:
    com:
      jialong:
        powersite: debug