spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jialong?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml

server:
  servlet:
    context-path: /jialong

---
server:
  port: 80
spring:
  profiles: dev


---
server:
  port: 80
spring:
  profiles:
    active: prod